/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panel;

import entity.user;
import javax.swing.SwingUtilities;
import main.main;
import repository.userRepository;
import service.Auth;

/**
 *
 * @author RESCOM-1
 */
public class daftarakun_tambah extends javax.swing.JPanel {
    userRepository a = new userRepository();
    /**
     * Creates new form daftarakun_tambah
     */
    public daftarakun_tambah() {
        initComponents();
        
        txt_id.setText(String.valueOf(a.getlastid().getId() + 1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_password = new javax.swing.JTextField();
        txt_password2 = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        txt_username = new javax.swing.JTextField();
        txt_id = new javax.swing.JTextField();
        btnbatal = new javax.swing.JLabel();
        btnselanjutnya = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setLayout(null);
        add(txt_password);
        txt_password.setBounds(630, 440, 480, 40);
        add(txt_password2);
        txt_password2.setBounds(630, 510, 480, 40);
        add(txt_email);
        txt_email.setBounds(630, 580, 480, 40);
        add(txt_username);
        txt_username.setBounds(630, 370, 480, 40);
        add(txt_id);
        txt_id.setBounds(630, 300, 480, 40);

        btnbatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btnbatalpojok1.png"))); // NOI18N
        btnbatal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnbatalMouseClicked(evt);
            }
        });
        add(btnbatal);
        btnbatal.setBounds(10, 700, 150, 60);

        btnselanjutnya.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btnselanjutnya1.png"))); // NOI18N
        btnselanjutnya.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnselanjutnyaMouseClicked(evt);
            }
        });
        add(btnselanjutnya);
        btnselanjutnya.setBounds(1110, 700, 250, 60);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebg/bg user baru.png"))); // NOI18N
        add(bg);
        bg.setBounds(0, 0, 1366, 768);
    }// </editor-fold>//GEN-END:initComponents

    private void btnbatalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbatalMouseClicked
      main wow = (main)SwingUtilities.getWindowAncestor(this);
        this.setVisible(false);
        wow.showdaftar_akun();
    }//GEN-LAST:event_btnbatalMouseClicked

    private void btnselanjutnyaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnselanjutnyaMouseClicked
        Auth appa = new Auth();
        if (!txt_email.getText().equals("") || !txt_username.equals("") || !txt_password.equals("") || !txt_password2.equals("") ) {
            
        
        if(txt_password.getText().equals(txt_password2.getText())){
          String password = txt_password.getText();
          user apa = new user(txt_username.getText(), password, txt_email.getText(), 2,0);
          a.add(apa);
          appa.hapusToken(txt_username.getText());
          main wow = (main)SwingUtilities.getWindowAncestor(this);
        this.setVisible(false);
        wow.showdaftar_akun();
      } else {
          System.out.println("pssword dan confirm password harus sama");
      }
        } else {
            System.out.println("data tidak valid");
        }
    }//GEN-LAST:event_btnselanjutnyaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JLabel btnbatal;
    private javax.swing.JLabel btnselanjutnya;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_password;
    private javax.swing.JTextField txt_password2;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
