/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panel;

import entity.user;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import main.main;
import repository.userRepository;

/**
 *
 * @author semafie
 */
public class daftarakun extends javax.swing.JPanel {
    userRepository datamaster = new userRepository();
    public static int id;
    /**
     * Creates new form daftarakun
     */
    public daftarakun() {
        initComponents();
        load_tabel();
        
    }
    public void load_tabel(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID");
        model.addColumn("USERNAME");
        model.addColumn("PASWWORD");
        model.addColumn("EMAIL");
    
        try {
            for(user apa:datamaster.get()){
                model.addRow(new Object[]{
                    apa.getId(),
                    apa.getUsername(),
                    apa.getPassword(),
                    apa.getEmail()      

                });
            }
            table.setModel(model);
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new view.swing.Table();
        btnkeluar = new javax.swing.JLabel();
        btntambah = new javax.swing.JLabel();
        btnedit = new javax.swing.JLabel();
        btnhapus = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setLayout(null);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        add(jScrollPane1);
        jScrollPane1.setBounds(70, 270, 1230, 370);

        btnkeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btnkembali1.png"))); // NOI18N
        btnkeluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnkeluarMouseClicked(evt);
            }
        });
        add(btnkeluar);
        btnkeluar.setBounds(20, 700, 190, 51);

        btntambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btntambah1.png"))); // NOI18N
        btntambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btntambahMouseClicked(evt);
            }
        });
        add(btntambah);
        btntambah.setBounds(40, 150, 200, 70);

        btnedit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btnedit1.png"))); // NOI18N
        btnedit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btneditMouseClicked(evt);
            }
        });
        add(btnedit);
        btnedit.setBounds(260, 150, 200, 70);

        btnhapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btnhapus1.png"))); // NOI18N
        btnhapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnhapusMouseClicked(evt);
            }
        });
        add(btnhapus);
        btnhapus.setBounds(480, 150, 200, 70);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebg/bg datamaster.png"))); // NOI18N
        add(bg);
        bg.setBounds(1, 2, 1370, 770);
    }// </editor-fold>//GEN-END:initComponents

    private void btnkeluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnkeluarMouseClicked
    main wow = (main)SwingUtilities.getWindowAncestor(this);
        this.setVisible(false);
        wow.showdasboardowner();
    }//GEN-LAST:event_btnkeluarMouseClicked

    private void btntambahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btntambahMouseClicked
    main main =(main)SwingUtilities.getWindowAncestor(this);
    this.setVisible(false);
    main.showdaftar_akuntambah();
    }//GEN-LAST:event_btntambahMouseClicked

    private void btneditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btneditMouseClicked
    if(id != 0){
        main main =(main)SwingUtilities.getWindowAncestor(this);
    this.setVisible(false);
    main.showdaftar_akunedit();
    } else {
        System.out.println("pilih dulu bang tabelnya");
    }
    }//GEN-LAST:event_btneditMouseClicked

    private void btnhapusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhapusMouseClicked
        userRepository dokter = new userRepository();
        if(id != 0){
            dokter.delete(id);
            System.out.println("berhasil hapus");
        } else {
            System.out.println("gagal hapus");
        }
        load_tabel();
    }//GEN-LAST:event_btnhapusMouseClicked

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
    int baris = table.rowAtPoint(evt.getPoint());
        String idd = table.getValueAt(baris, 0).toString();
        id = Integer.valueOf(idd);
        System.out.println(id);
    }//GEN-LAST:event_tableMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JLabel btnedit;
    private javax.swing.JLabel btnhapus;
    private javax.swing.JLabel btnkeluar;
    private javax.swing.JLabel btntambah;
    private javax.swing.JScrollPane jScrollPane1;
    private view.swing.Table table;
    // End of variables declaration//GEN-END:variables
}
