/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panel;

/**
 *
 * @author semafie
 */
public class dasboardowner extends javax.swing.JPanel {

    /**
     * Creates new form dasboardowner
     */
    public dasboardowner() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnhistorydatamaster = new javax.swing.JLabel();
        btndaftarakun = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setLayout(null);

        btnhistorydatamaster.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btn_historydatamaster1.png"))); // NOI18N
        add(btnhistorydatamaster);
        btnhistorydatamaster.setBounds(560, 300, 414, 100);

        btndaftarakun.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btn_daftarakun1.png"))); // NOI18N
        add(btndaftarakun);
        btndaftarakun.setBounds(260, 160, 420, 100);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebg/bg dasboard.png"))); // NOI18N
        add(bg);
        bg.setBounds(0, 0, 1366, 768);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JLabel btndaftarakun;
    private javax.swing.JLabel btnhistorydatamaster;
    // End of variables declaration//GEN-END:variables
}
