/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panel;

import javax.swing.SwingUtilities;
import main.main;

/**
 *
 * @author RESCOM-1
 */
public class Dasboard extends javax.swing.JPanel {

    /**
     * Creates new form Dasboard
     */
    public Dasboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btndatamaster = new javax.swing.JLabel();
        btndatadokter = new javax.swing.JLabel();
        btnpasienbaru = new javax.swing.JLabel();
        btnpasienlama = new javax.swing.JLabel();
        btnrekapharian = new javax.swing.JLabel();
        btnlogout = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1366, 768));
        setLayout(null);

        btndatamaster.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btndatamaster1.png"))); // NOI18N
        btndatamaster.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btndatamasterMouseClicked(evt);
            }
        });
        add(btndatamaster);
        btndatamaster.setBounds(200, 150, 380, 100);

        btndatadokter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btndatadokter1.png"))); // NOI18N
        btndatadokter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btndatadokterMouseClicked(evt);
            }
        });
        add(btndatadokter);
        btndatadokter.setBounds(620, 150, 380, 100);

        btnpasienbaru.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btnpasienbaru1.png"))); // NOI18N
        btnpasienbaru.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnpasienbaruMouseClicked(evt);
            }
        });
        add(btnpasienbaru);
        btnpasienbaru.setBounds(420, 290, 370, 140);

        btnpasienlama.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btnpasienlama1.png"))); // NOI18N
        btnpasienlama.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnpasienlamaMouseClicked(evt);
            }
        });
        add(btnpasienlama);
        btnpasienlama.setBounds(720, 450, 360, 130);

        btnrekapharian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btnrekapharian1.png"))); // NOI18N
        btnrekapharian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnrekapharianMouseClicked(evt);
            }
        });
        add(btnrekapharian);
        btnrekapharian.setBounds(930, 610, 380, 90);

        btnlogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btnlogout1.png"))); // NOI18N
        btnlogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnlogoutMouseClicked(evt);
            }
        });
        add(btnlogout);
        btnlogout.setBounds(20, 700, 180, 51);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebg/bg dasboard.png"))); // NOI18N
        add(bg);
        bg.setBounds(0, -2, 1366, 770);
    }// </editor-fold>//GEN-END:initComponents

    private void btndatamasterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndatamasterMouseClicked
    main main =(main)SwingUtilities.getWindowAncestor(this);
    this.setVisible(false);
    main.showdatamaster();
    }//GEN-LAST:event_btndatamasterMouseClicked

    private void btndatadokterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndatadokterMouseClicked
    main main =(main)SwingUtilities.getWindowAncestor(this);
    this.setVisible(false);
    main.showdatadokter();
    }//GEN-LAST:event_btndatadokterMouseClicked

    private void btnpasienbaruMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnpasienbaruMouseClicked
    pasienbaru a = new pasienbaru();
//    a.txt_alamat.setText("");
//    a.txt_nama_pasien.setText("");
//    a.txt_nik.setText("");
//    a.txt_no_rm.setText("");
//    a.txt_ttl.setText("");
    main main =(main)SwingUtilities.getWindowAncestor(this);
    this.setVisible(false);
    main.showpasienbaru();
    }//GEN-LAST:event_btnpasienbaruMouseClicked

    private void btnpasienlamaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnpasienlamaMouseClicked
    main main =(main)SwingUtilities.getWindowAncestor(this);
    this.setVisible(false);
    main.showpasienlama();
    }//GEN-LAST:event_btnpasienlamaMouseClicked

    private void btnrekapharianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnrekapharianMouseClicked
    main main =(main)SwingUtilities.getWindowAncestor(this);
    this.setVisible(false);
    main.showrekapharian();
    }//GEN-LAST:event_btnrekapharianMouseClicked

    private void btnlogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlogoutMouseClicked
    main main =(main)SwingUtilities.getWindowAncestor(this);
    this.setVisible(false);
    main.showlogin();
    }//GEN-LAST:event_btnlogoutMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JLabel btndatadokter;
    private javax.swing.JLabel btndatamaster;
    private javax.swing.JLabel btnlogout;
    private javax.swing.JLabel btnpasienbaru;
    private javax.swing.JLabel btnpasienlama;
    private javax.swing.JLabel btnrekapharian;
    // End of variables declaration//GEN-END:variables
}
