/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panel;

import entity.data_master;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import main.main;
import repository.data_masterRepository;
import util.Conn;

/**
 *
 * @author RESCOM-1
 */
public class pasienlama extends javax.swing.JPanel {
    data_masterRepository datamaster = new data_masterRepository();
    /**
     * Creates new form pasienlama
     */
    public pasienlama() {
        initComponents();
        load_tabel();
    }
    public void load_tabel(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("NO_RM");
        model.addColumn("NAMA");
        model.addColumn("JENIS_KELAMIN");
        try {
            for(data_master apa:datamaster.get()){
                model.addRow(new Object[]{
                    apa.getNo_rm(),
                    apa.getNama(),
                    apa.getJenis_kelamin()
                });
            }
            table.setModel(model);
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }
    
    public void load_search(String search) {
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("NO_RM");
    model.addColumn("NAMA");
    model.addColumn("JENIS_KELAMIN");
    
    try {
        String sql = "SELECT * FROM data_master WHERE no_rm LIKE ? OR nama LIKE ? OR jenis_kelamin LIKE ?";
        Connection koneksi = (Connection)Conn.configDB();
        PreparedStatement pst = koneksi.prepareStatement(sql);
        pst.setString(1, "%" + search + "%");
        pst.setString(2, "%" + search + "%");
        pst.setString(3, "%" + search + "%");

        ResultSet res = pst.executeQuery();

        while (res.next()) {
            model.addRow(new Object[]{
                res.getString("no_rm"),
                res.getString("nama"),
                res.getString("jenis_kelamin")
            });
        }

        table.setModel(model);
    } catch (Exception e) {
        e.printStackTrace();
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new view.swing.Table();
        searchlo = new javax.swing.JTextField();
        btnkembali = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setLayout(null);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table);

        add(jScrollPane1);
        jScrollPane1.setBounds(100, 290, 1190, 370);

        searchlo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchloKeyReleased(evt);
            }
        });
        add(searchlo);
        searchlo.setBounds(260, 210, 240, 50);

        btnkembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btnbatal1 (1).png"))); // NOI18N
        btnkembali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnkembaliMouseClicked(evt);
            }
        });
        add(btnkembali);
        btnkembali.setBounds(10, 710, 180, 51);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebg/bg pasien lama.png"))); // NOI18N
        add(bg);
        bg.setBounds(0, 0, 1366, 774);
    }// </editor-fold>//GEN-END:initComponents

    private void searchloKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchloKeyReleased
        load_search(searchlo.getText());
    }//GEN-LAST:event_searchloKeyReleased

    private void btnkembaliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnkembaliMouseClicked
    main main =(main)SwingUtilities.getWindowAncestor(this);
    this.setVisible(false);
    main.showdasboard();
    }//GEN-LAST:event_btnkembaliMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JLabel btnkembali;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField searchlo;
    private view.swing.Table table;
    // End of variables declaration//GEN-END:variables
}
