/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panel;

import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.SwingUtilities;
import main.main;

/**
 *
 * @author Be Mine
 */
public class pasienbaru_tambahdaftar extends javax.swing.JPanel {
    
    private int id;
    /**
     * Creates new form tambahdaftar
     */
    public pasienbaru_tambahdaftar() {
        initComponents();
        Date tanggalHariIni = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
        String tanggalString = sdf.format(tanggalHariIni);
        tanggal.setText(tanggalString);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_dokter = new javax.swing.JTextField();
        txt_nama = new javax.swing.JTextField();
        txt_no = new javax.swing.JTextField();
        btnsimpandancetaknoantrian = new javax.swing.JLabel();
        btnbatal = new javax.swing.JLabel();
        btnkembali = new javax.swing.JLabel();
        tanggal = new javax.swing.JLabel();
        cmb_poli = new javax.swing.JComboBox<>();
        cmb_jeniskelamin = new javax.swing.JComboBox<>();
        bg = new javax.swing.JLabel();
        nik = new javax.swing.JTextField();
        alamat = new javax.swing.JTextField();
        ttl = new javax.swing.JTextField();
        nama_pasien = new javax.swing.JTextField();
        no_rm = new javax.swing.JTextField();

        setLayout(null);

        txt_dokter.setBorder(null);
        add(txt_dokter);
        txt_dokter.setBounds(530, 410, 530, 50);

        txt_nama.setBorder(null);
        add(txt_nama);
        txt_nama.setBounds(530, 332, 530, 50);

        txt_no.setBorder(null);
        add(txt_no);
        txt_no.setBounds(530, 252, 530, 50);

        btnsimpandancetaknoantrian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btnsimpandancetaknoantrian1.png"))); // NOI18N
        add(btnsimpandancetaknoantrian);
        btnsimpandancetaknoantrian.setBounds(780, 700, 544, 50);

        btnbatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btnbatal3.png"))); // NOI18N
        btnbatal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnbatalMouseClicked(evt);
            }
        });
        add(btnbatal);
        btnbatal.setBounds(520, 700, 260, 50);

        btnkembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btnkembali1.png"))); // NOI18N
        btnkembali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnkembaliMouseClicked(evt);
            }
        });
        add(btnkembali);
        btnkembali.setBounds(10, 700, 200, 60);
        add(tanggal);
        tanggal.setBounds(1080, 50, 170, 30);

        cmb_poli.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Poli umum", "Poli gigi", "Poli mata" }));
        add(cmb_poli);
        cmb_poli.setBounds(570, 490, 290, 50);

        cmb_jeniskelamin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki - Laki", "Perempuan" }));
        add(cmb_jeniskelamin);
        cmb_jeniskelamin.setBounds(570, 570, 290, 50);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebg/bg tambah daftar.png"))); // NOI18N
        add(bg);
        bg.setBounds(0, 0, 1366, 768);
        add(nik);
        nik.setBounds(550, 390, 490, 40);
        add(alamat);
        alamat.setBounds(550, 460, 490, 40);
        add(ttl);
        ttl.setBounds(550, 530, 490, 40);
        add(nama_pasien);
        nama_pasien.setBounds(550, 320, 490, 40);
        add(no_rm);
        no_rm.setBounds(550, 250, 490, 40);
    }// </editor-fold>//GEN-END:initComponents

    private void btnkembaliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnkembaliMouseClicked
    main main =(main)SwingUtilities.getWindowAncestor(this);
    this.setVisible(false);
    main.showpasienbaru_pilihdokter();
    }//GEN-LAST:event_btnkembaliMouseClicked

    private void btnbatalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbatalMouseClicked
    
    }//GEN-LAST:event_btnbatalMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamat;
    private javax.swing.JLabel bg;
    private javax.swing.JLabel btnbatal;
    private javax.swing.JLabel btnkembali;
    private javax.swing.JLabel btnsimpandancetaknoantrian;
    private javax.swing.JComboBox<String> cmb_jeniskelamin;
    private javax.swing.JComboBox<String> cmb_poli;
    private javax.swing.JTextField nama_pasien;
    private javax.swing.JTextField nik;
    private javax.swing.JTextField no_rm;
    private javax.swing.JLabel tanggal;
    private javax.swing.JTextField ttl;
    private javax.swing.JTextField txt_dokter;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JTextField txt_no;
    // End of variables declaration//GEN-END:variables
}
