/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panel;

import entity.pasienbaru_sementara;
import javax.swing.SwingUtilities;
import main.main;

import repository.datapasienbarusementara;
import repository.pasienbaru_sementaraRepository;

/**
 *
 * @author semafie
 */
public class pasienbaru1 extends javax.swing.JPanel {
    
    pasienbaru_sementaraRepository bb = new pasienbaru_sementaraRepository();
    public pasienbaru1() {
        initComponents();
        txt_no_rm.setText(String.valueOf(bb.get(1).getId()));
        txt_nama_pasien.setText(bb.get(1).getNama());
        txt_alamat.setText(bb.get(1).getAlamat());
        txt_nik.setText(String.valueOf(bb.get(1).getNik()));
        txt_ttl.setText(bb.get(1).getTtl());
        if (bb.get(1).getJenis_kelamin().equals("Laki - Laki")) {
            cmd_jnk.setSelectedIndex(0);
        } else {
            cmd_jnk.setSelectedIndex(1);
        }
//        Object selectedItem = cmd_jnk.getSelectedItem();   
//        String jnk = selectedItem.toString();
//        System.out.println(jnk);
        
    }
    
    public void apek(){

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_kembali = new javax.swing.JLabel();
        btn_lanjut = new javax.swing.JLabel();
        txt_nik = new javax.swing.JTextField();
        txt_alamat = new javax.swing.JTextField();
        txt_ttl = new javax.swing.JTextField();
        txt_nama_pasien = new javax.swing.JTextField();
        txt_no_rm = new javax.swing.JTextField();
        cmd_jnk = new javax.swing.JComboBox<>();
        bg = new javax.swing.JLabel();
        cacacac = new javax.swing.JTextField();

        setLayout(null);

        btn_kembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btnkembali1.png"))); // NOI18N
        btn_kembali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_kembaliMouseClicked(evt);
            }
        });
        add(btn_kembali);
        btn_kembali.setBounds(10, 701, 190, 60);

        btn_lanjut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btnselanjutnya1.png"))); // NOI18N
        btn_lanjut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_lanjutMouseClicked(evt);
            }
        });
        add(btn_lanjut);
        btn_lanjut.setBounds(1110, 701, 250, 60);
        add(txt_nik);
        txt_nik.setBounds(550, 390, 490, 40);
        add(txt_alamat);
        txt_alamat.setBounds(550, 460, 490, 40);
        add(txt_ttl);
        txt_ttl.setBounds(550, 530, 490, 40);
        add(txt_nama_pasien);
        txt_nama_pasien.setBounds(550, 320, 490, 40);
        add(txt_no_rm);
        txt_no_rm.setBounds(550, 250, 490, 40);

        cmd_jnk.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki - Laki", "Perempuan" }));
        add(cmd_jnk);
        cmd_jnk.setBounds(570, 600, 280, 40);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebg/Pasien Baru.png"))); // NOI18N
        add(bg);
        bg.setBounds(0, 0, 1366, 768);

        cacacac.setText("jTextField1");
        add(cacacac);
        cacacac.setBounds(310, 180, 71, 22);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_kembaliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_kembaliMouseClicked
    main main =(main)SwingUtilities.getWindowAncestor(this);
    this.setVisible(false);
    main.showdasboard();
    }//GEN-LAST:event_btn_kembaliMouseClicked

    private void btn_lanjutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_lanjutMouseClicked
//int no = Integer.valueOf(txt_no_rm.getText());
        String nama = txt_nama_pasien.getText();
        int nik = Integer.valueOf(txt_nik.getText());
        String ttl = txt_ttl.getText();
        String alamat = txt_alamat.getText();
        Object selectedItem = cmd_jnk.getSelectedItem();   
        String jnk = selectedItem.toString();
        System.out.println(jnk);
        pasienbaru_sementara aa = new pasienbaru_sementara(1, nama, nik, alamat, ttl, jnk);
        bb.update(aa);
//        if (txt_no_rm.getText().equals("") || txt_nik.getText().equals("") || txt_alamat.getText().equals("") || txt_nama_pasien.getText().equals("") || txt_ttl.getText().equals("")) {
//            System.out.println("isi data sek muas");
//        } else {
//            
//        }
        main main =(main)SwingUtilities.getWindowAncestor(this);
        this.setVisible(false);
        main.showpasienbaru_pilihpoli();
    }//GEN-LAST:event_btn_lanjutMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JLabel btn_kembali;
    private javax.swing.JLabel btn_lanjut;
    private javax.swing.JTextField cacacac;
    private javax.swing.JComboBox<String> cmd_jnk;
    public static javax.swing.JTextField txt_alamat;
    public static javax.swing.JTextField txt_nama_pasien;
    public static javax.swing.JTextField txt_nik;
    public static javax.swing.JTextField txt_no_rm;
    public static javax.swing.JTextField txt_ttl;
    // End of variables declaration//GEN-END:variables
}
