/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panel;

import javax.swing.SwingUtilities;
import main.main;

/**
 *
 * @author RESCOM-1
 */
public class pasienbaru_pilihpoli extends javax.swing.JPanel {

    /**
     * Creates new form pasienbaru_pilihpoli
     */
    public pasienbaru_pilihpoli() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnlanjut = new javax.swing.JLabel();
        btnbatal = new javax.swing.JLabel();
        itempoli_tampilan1 = new view.swing.itempoli_tampilan();
        bg = new javax.swing.JLabel();

        setLayout(null);

        btnlanjut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btnselanjutnya1.png"))); // NOI18N
        btnlanjut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnlanjutMouseClicked(evt);
            }
        });
        add(btnlanjut);
        btnlanjut.setBounds(1110, 701, 250, 60);

        btnbatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btnbatalpojok1.png"))); // NOI18N
        btnbatal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnbatalMouseClicked(evt);
            }
        });
        add(btnbatal);
        btnbatal.setBounds(10, 701, 150, 60);
        add(itempoli_tampilan1);
        itempoli_tampilan1.setBounds(230, 230, 490, 390);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebg/bg pilih poli.png"))); // NOI18N
        add(bg);
        bg.setBounds(0, 0, 1366, 768);
    }// </editor-fold>//GEN-END:initComponents

    private void btnlanjutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlanjutMouseClicked
    
    }//GEN-LAST:event_btnlanjutMouseClicked

    private void btnbatalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbatalMouseClicked
    main main =(main)SwingUtilities.getWindowAncestor(this);
    this.setVisible(false);
    main.showpasienbaru();
    }//GEN-LAST:event_btnbatalMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JLabel btnbatal;
    private javax.swing.JLabel btnlanjut;
    private view.swing.itempoli_tampilan itempoli_tampilan1;
    // End of variables declaration//GEN-END:variables
}
