/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panel;

/**
 *
 * @author Be Mine
 */
public class pilihdokter extends javax.swing.JPanel {

    /**
     * Creates new form pilihdokter
     */
    public pilihdokter() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnselanjutnya = new javax.swing.JLabel();
        btnkembali = new javax.swing.JLabel();
        bgpilihdokter = new javax.swing.JLabel();

        setLayout(null);

        btnselanjutnya.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btnselanjutnya1.png"))); // NOI18N
        add(btnselanjutnya);
        btnselanjutnya.setBounds(1080, 695, 250, 60);

        btnkembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btnkembali1.png"))); // NOI18N
        add(btnkembali);
        btnkembali.setBounds(40, 695, 210, 60);

        bgpilihdokter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebg/bg pilih dokter.png"))); // NOI18N
        add(bgpilihdokter);
        bgpilihdokter.setBounds(0, 0, 1366, 768);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgpilihdokter;
    private javax.swing.JLabel btnkembali;
    private javax.swing.JLabel btnselanjutnya;
    // End of variables declaration//GEN-END:variables
}
