/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panel;

import javax.swing.table.DefaultTableModel;
import repository.rekap_harianRepository;
import entity.rekap_harian;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.SwingUtilities;
import main.main;
import repository.data_dokterRepository;
import repository.data_masterRepository;
import util.Conn;
        

/**
 *
 * @author semafie
 */
public class rekapharian1 extends javax.swing.JPanel {
    rekap_harianRepository gege = new rekap_harianRepository();
    data_dokterRepository gege1 = new data_dokterRepository();
    data_masterRepository gege2 = new data_masterRepository();
    private int id;
    private int id1;
    Date date;
    SimpleDateFormat timeFormat = new SimpleDateFormat("HH:mm:ss");
    /**
     * Creates new form rekap_harian
     */
    public rekapharian1() {
        initComponents();
        load_tabel2();
    }
    public void load_tabel(){
        
        
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID");
        model.addColumn("NO RM");
        model.addColumn("NAMA PASIEN");
        model.addColumn("JENISKELAMIN");
        model.addColumn("NAMA DOKTER");
        model.addColumn("JENIS POLI");
        model.addColumn("JAM");
        try {
            for(rekap_harian apa:gege.get()){
                model.addRow(new Object[]{
                    apa.getId(),
                    apa.getData_master().getNo_rm(),
                    apa.getData_master().getNama(),
                    apa.getData_master().getJenis_kelamin(),
                    apa.getData_dokter().getNama(),
                    apa.getData_dokter().getJenis_poli(),
                    timeFormat.format(new Date(apa.getJam().getTime()))
                });
            }
            table.setModel(model);
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }
    public void load_tabel2(){
        
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID");
        model.addColumn("NO RM");
        model.addColumn("NAMA PASIEN");
        model.addColumn("JENISKELAMIN");
        model.addColumn("NAMA DOKTER");
        model.addColumn("JENIS POLI");
        model.addColumn("JAM");
        
        try {
        String sql = "SELECT * FROM rekap_harian join data_dokter on rekap_harian.id_dokter = data_dokter.id join data_master on rekap_harian.id_master = data_master.id";
        Connection koneksi = (Connection)Conn.configDB();
        PreparedStatement pst = koneksi.prepareStatement(sql);

        ResultSet res = pst.executeQuery();

        while (res.next()) {
            model.addRow(new Object[]{
                res.getInt("id"),
                res.getString("no_rm"),
                res.getString("nama1"),
                res.getString("jenis_kelamin1"),
                res.getString("nama"),
                res.getString("jenis_poli"),
                res.getTime("jam")
            });
        }

        table.setModel(model);
    } catch (Exception e) {
        e.printStackTrace();
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new view.swing.Table();
        jLabel1 = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setLayout(null);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table);

        add(jScrollPane1);
        jScrollPane1.setBounds(100, 200, 1190, 402);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btnbatal1 (1).png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        add(jLabel1);
        jLabel1.setBounds(10, 700, 200, 50);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebg/bg rekap harian.png"))); // NOI18N
        add(bg);
        bg.setBounds(0, 0, 1366, 762);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
    main main =(main)SwingUtilities.getWindowAncestor(this);
    this.setVisible(false);
    main.showdasboard();
    }//GEN-LAST:event_jLabel1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private view.swing.Table table;
    // End of variables declaration//GEN-END:variables
}
