/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panel;
import java.awt.Color;
import entity.user;
import java.awt.Font;
import javax.swing.SwingUtilities;
import main.main;
import repository.userRepository;
import service.Auth;
import view.swing.validasiberhasil;

/**
 *
 * @author RESCOM-1
 */
public class daftarakun_tambah extends javax.swing.JPanel {
    userRepository a = new userRepository();
    /**
     * Creates new form daftarakun_tambah
     */
    public daftarakun_tambah() {
        initComponents();
        Font font = new Font("Quicksand", Font.PLAIN, 22);
        txt_email.setFont(font);
        txt_id.setFont(font);
        txt_password.setFont(font);
        txt_password2.setFont(font);
        txt_username.setFont(font);
        txt_id.setText(String.valueOf(a.getlastid().getId() + 1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_password = new javax.swing.JTextField();
        txt_password2 = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        txt_username = new javax.swing.JTextField();
        txt_id = new javax.swing.JTextField();
        btnbatal = new javax.swing.JLabel();
        btnselanjutnya = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setLayout(null);

        txt_password.setBackground(new Color(0,0,0,0));
        txt_password.setBorder(null);
        add(txt_password);
        txt_password.setBounds(630, 440, 480, 40);

        txt_password2.setBackground(new Color(0,0,0,0));
        txt_password2.setBorder(null);
        add(txt_password2);
        txt_password2.setBounds(630, 510, 480, 40);

        txt_email.setBackground(new Color(0,0,0,0));
        txt_email.setBorder(null);
        add(txt_email);
        txt_email.setBounds(630, 580, 480, 40);

        txt_username.setBackground(new Color(0,0,0,0));
        txt_username.setBorder(null);
        add(txt_username);
        txt_username.setBounds(630, 370, 480, 40);

        txt_id.setBackground(new Color(0,0,0,0));
        txt_id.setBorder(null);
        txt_id.setFocusable(false);
        add(txt_id);
        txt_id.setBounds(630, 300, 480, 40);

        btnbatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btnbatal1_1.png"))); // NOI18N
        btnbatal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnbatalMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnbatalMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnbatalMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnbatalMousePressed(evt);
            }
        });
        add(btnbatal);
        btnbatal.setBounds(10, 700, 150, 60);

        btnselanjutnya.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btnselanjutnya1.png"))); // NOI18N
        btnselanjutnya.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnselanjutnyaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnselanjutnyaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnselanjutnyaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnselanjutnyaMousePressed(evt);
            }
        });
        add(btnselanjutnya);
        btnselanjutnya.setBounds(1110, 700, 250, 60);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebg/bg user baru.png"))); // NOI18N
        add(bg);
        bg.setBounds(0, 0, 1366, 768);
    }// </editor-fold>//GEN-END:initComponents

    private void btnbatalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbatalMouseClicked
      main wow = (main)SwingUtilities.getWindowAncestor(this);
        this.setVisible(false);
        wow.showdaftar_akun();
    }//GEN-LAST:event_btnbatalMouseClicked

    private void btnselanjutnyaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnselanjutnyaMouseClicked
        Auth appa = new Auth();
        if (!txt_email.getText().equals("") || !txt_username.equals("") || !txt_password.equals("") || !txt_password2.equals("") ) {
            
        
        if(txt_password.getText().equals(txt_password2.getText())){
          String password = txt_password.getText();
          user apa = new user(Integer.valueOf(txt_id.getText()),txt_username.getText(), password, txt_email.getText(), 2,0);
          a.add(apa);
          appa.hapusToken(txt_username.getText());
          main wow = (main)SwingUtilities.getWindowAncestor(this);
        this.setVisible(false);
        wow.showdaftar_akun();
        validasiberhasil ac = new validasiberhasil(wow, "Data Berhasil Ditambahkan");
            ac.showPopUp();
      } else {
          System.out.println("pssword dan confirm password harus sama");
      }
        } else {
            System.out.println("data tidak valid");
        }
    }//GEN-LAST:event_btnselanjutnyaMouseClicked

    private void btnbatalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbatalMouseEntered
    btnbatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btnbatal2_1.png")));
    }//GEN-LAST:event_btnbatalMouseEntered

    private void btnbatalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbatalMouseExited
    btnbatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btnbatal1_1.png")));
    }//GEN-LAST:event_btnbatalMouseExited

    private void btnbatalMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbatalMousePressed
   btnbatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btnbatal3_1.png")));
    }//GEN-LAST:event_btnbatalMousePressed

    private void btnselanjutnyaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnselanjutnyaMouseEntered
    btnselanjutnya.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btnselanjutnya2.png")));
    }//GEN-LAST:event_btnselanjutnyaMouseEntered

    private void btnselanjutnyaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnselanjutnyaMouseExited
    btnselanjutnya.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btnselanjutnya1.png")));
    }//GEN-LAST:event_btnselanjutnyaMouseExited

    private void btnselanjutnyaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnselanjutnyaMousePressed
    btnselanjutnya.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btnselanjutnya3.png")));
    }//GEN-LAST:event_btnselanjutnyaMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JLabel btnbatal;
    private javax.swing.JLabel btnselanjutnya;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_password;
    private javax.swing.JTextField txt_password2;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
