/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panel;
import java.awt.Color;
import entity.data_master;
import java.awt.Font;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.EventObject;
import javax.swing.DefaultCellEditor;

import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import main.main;
import panel.datamaster_edit;
import repository.data_masterRepository;
import util.Conn;
import view.swing.validasiberhasil1;
import view.swing.validasiberhasil2;
import view.swing.validasigagal;

/**
 *
 * @author RESCOM-1
 */
public class datamaster extends javax.swing.JPanel {
    data_masterRepository datamaster = new data_masterRepository();
    public static String ids;
    public static int id;
//    datamaster_edit edit = new datamaster_edit();
    /**
     * Creates new form datamaster
     */
    public datamaster() {
        initComponents();
        DefaultCellEditor cellEditor = new DefaultCellEditor(new JTextField()) {
    @Override
    public boolean isCellEditable(EventObject e) {
        return false;
    }
};
        table.setDefaultEditor(Object.class, cellEditor);
        load_tabel();
        Font font = new Font("Quicksand", Font.PLAIN, 22);
        search.setFont(font);
       
        table.setDefaultEditor(Object.class, cellEditor);
    }
    public void load_tabel(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("NO_RM");
        model.addColumn("NAMA");
        model.addColumn("NIK");
        model.addColumn("ALAMAT");
        model.addColumn("TTL");
        model.addColumn("JENIS_KELAMIN");
        model.addColumn("STATUS_BAYAR");
        try {
            for(data_master apa:datamaster.get()){
                model.addRow(new Object[]{
                    apa.getNo_rm(),
                    apa.getNama(),
                    apa.getNik(),
                    apa.getAlamat(),
                    apa.getTtl(),
                    apa.getJenis_kelamin(),
                    apa.getStatus_pembayaran()
                });
            }
            table.setModel(model);
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }
    public void load_search(String search) {
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("NO_RM");
    model.addColumn("NAMA");
    model.addColumn("NIK");
    model.addColumn("ALAMAT");
    model.addColumn("TTL");
    model.addColumn("JENIS_KELAMIN");
    model.addColumn("STATUS_BAYAR");
    
    try {
        String sql = "SELECT * FROM data_master WHERE no_rm = ? OR nama1 LIKE ? OR nik LIKE ?";
        Connection koneksi = (Connection)Conn.configDB();
        PreparedStatement pst = koneksi.prepareStatement(sql);
        pst.setString(1, "%" + search + "%");
        pst.setString(2, "%" + search + "%");
        pst.setString(3, "%" + search + "%");

        ResultSet res = pst.executeQuery();

        while (res.next()) {
            model.addRow(new Object[]{
                res.getString("no_rm"),
                res.getString("nama1"),
                res.getString("nik"),
                res.getString("alamat"),
                res.getString("ttl"),
                res.getString("jenis_kelamin1"),
                res.getString("status_pembayaran")
            });
        }

        table.setModel(model);
    } catch (Exception e) {
        e.printStackTrace();
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnkembali = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new view.swing.Table();
        search = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnedit = new javax.swing.JLabel();
        btnhapus = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setLayout(null);

        btnkembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btnkembali1.png"))); // NOI18N
        btnkembali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnkembaliMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnkembaliMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnkembaliMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnkembaliMousePressed(evt);
            }
        });
        add(btnkembali);
        btnkembali.setBounds(10, 710, 190, 51);

        jScrollPane2.setBackground(new java.awt.Color(227, 252, 246));
        jScrollPane2.setBorder(null);

        table.setBackground(new java.awt.Color(227, 252, 246));
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table);

        add(jScrollPane2);
        jScrollPane2.setBounds(62, 262, 1240, 380);

        search.setBackground(new Color(0,0,0,0)
        );
        search.setBorder(null);
        search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchKeyReleased(evt);
            }
        });
        add(search);
        search.setBounds(51, 150, 300, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/search.png"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(40, 140, 330, 60);

        btnedit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btnedit1.png"))); // NOI18N
        btnedit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btneditMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btneditMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btneditMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btneditMousePressed(evt);
            }
        });
        add(btnedit);
        btnedit.setBounds(390, 145, 200, 60);

        btnhapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btnhapus1.png"))); // NOI18N
        btnhapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnhapusMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnhapusMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnhapusMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnhapusMousePressed(evt);
            }
        });
        add(btnhapus);
        btnhapus.setBounds(600, 145, 200, 60);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebg/bg datamaster.png"))); // NOI18N
        add(bg);
        bg.setBounds(0, 0, 1366, 768);
    }// </editor-fold>//GEN-END:initComponents

    private void btnkembaliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnkembaliMouseClicked
    main main =(main)SwingUtilities.getWindowAncestor(this);
    this.setVisible(false);
    main.showdasboard();
    }//GEN-LAST:event_btnkembaliMouseClicked

    private void btneditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btneditMouseClicked
//    int baris = table.rowAtPoint(evt.getPoint());
//        String idd = table.getValueAt(baris, 0).toString();
//        id = Integer.valueOf(idd);
//        String nama = table.getValueAt(baris, 1).toString();
//        String nik = table.getValueAt(baris, 2).toString();
//        String alamat = table.getValueAt(baris, 3).toString();
//        String ttl = table.getValueAt(baris, 4).toString();
//        String jenis_kelamin = table.getValueAt(baris, 4).toString();
//        System.out.println(id);
        
        if(!ids.equals("")){
//        edit.txt_no_rm.setText(idd);
//        edit.txt_nama_pasien.setText(nama);
//        edit.txt_nik.setText(nik);
//        edit.txt_alamat.setText(alamat);
//        edit.txt_ttl.setText(ttl);
//        if (jenis_kelamin.equals("Laki-Laki")) {
//            edit.cmb_jeniskelamin.setSelectedItem("Laki-Laki");
//        } else {
//            edit.cmb_jeniskelamin.setSelectedItem("Perempuan");
//        }
        main main =(main)SwingUtilities.getWindowAncestor(this);
        this.setVisible(false);
        main.showdatamaster_edit();
    } else {
            System.out.println("pilih data dari tabel bang");
        }
    }//GEN-LAST:event_btneditMouseClicked

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
    int baris = table.rowAtPoint(evt.getPoint());
        String idd = table.getValueAt(baris, 0).toString();
        ids = idd;
        id = datamaster.getbyno_rm(ids).getId();
        
        System.out.println(id);
    }//GEN-LAST:event_tableMouseClicked

    private void btnhapusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhapusMouseClicked
//    int baris = table.rowAtPoint(evt.getPoint());
//        String idd = table.getValueAt(baris, 0).toString();
//        id = Integer.valueOf(idd);
    if(!ids.equals("")){
        
            try {
            boolean apa = datamaster.delete(id);
            main main =(main)SwingUtilities.getWindowAncestor(this);
        validasiberhasil2 ac = new validasiberhasil2(main);
            ac.showPopUp();
        } catch (Exception e) {
            main main =(main)SwingUtilities.getWindowAncestor(this);
                validasigagal ac = new validasigagal(main, "Data ini tidak akan bisa dihapus karena terhubung dengan rekap harian"
                        + "pilih data lain");
            ac.showPopUp();
            return;
        }
        
        System.out.println("berhasil hapus");
    } else {
        System.out.println("gagal hapus");
    }
    load_tabel();
    }//GEN-LAST:event_btnhapusMouseClicked

    private void searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyReleased
        load_search(search.getText());
    }//GEN-LAST:event_searchKeyReleased

    private void btnkembaliMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnkembaliMouseEntered
    btnkembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btnkembali2.png")));
    }//GEN-LAST:event_btnkembaliMouseEntered

    private void btnkembaliMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnkembaliMouseExited
    btnkembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btnkembali1.png")));
    }//GEN-LAST:event_btnkembaliMouseExited

    private void btnkembaliMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnkembaliMousePressed
    btnkembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btnkembali3.png")));
    }//GEN-LAST:event_btnkembaliMousePressed

    private void btneditMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btneditMouseEntered
    btnedit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btnedit2.png")));
    }//GEN-LAST:event_btneditMouseEntered

    private void btneditMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btneditMouseExited
    btnedit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btnedit1.png")));
    }//GEN-LAST:event_btneditMouseExited

    private void btneditMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btneditMousePressed
    btnedit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btnedit3.png")));
    }//GEN-LAST:event_btneditMousePressed

    private void btnhapusMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhapusMouseEntered
    btnhapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btnhapus2.png")));
    }//GEN-LAST:event_btnhapusMouseEntered

    private void btnhapusMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhapusMouseExited
    btnhapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btnhapus1.png")));
    }//GEN-LAST:event_btnhapusMouseExited

    private void btnhapusMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhapusMousePressed
    btnhapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btnhapus3.png")));
    }//GEN-LAST:event_btnhapusMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JLabel btnedit;
    private javax.swing.JLabel btnhapus;
    private javax.swing.JLabel btnkembali;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField search;
    private view.swing.Table table;
    // End of variables declaration//GEN-END:variables
}
