/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panel;

import java.awt.Color;
import entity.data_master;
import java.awt.Font;
import javax.swing.SwingUtilities;
import main.main;
import repository.data_masterRepository;
import view.swing.validasiberhasil;

/**
 *
 * @author RESCOM-1
 */
public class datamaster_edit extends javax.swing.JPanel {
    data_masterRepository master = new data_masterRepository();
    datamaster a = new datamaster();
    private int ids = a.id;
    private String se = a.ids;
    private String jnkk;
    /**
     * Creates new form datamaster_edit
     */
    public datamaster_edit() {
        initComponents();
        Font font = new Font("Quicksand", Font.PLAIN, 22);
        txt_alamat.setFont(font);
        txt_nama_pasien.setFont(font);
        txt_nik.setFont(font);
        txt_no_rm.setFont(font);
        txt_ttl.setFont(font);
        System.out.println(ids);
        tampil();

    }
    public void tampil(){
//        int id = master.get(ids).getId();
        String nama = master.get(ids).getNama();
        String alamat = master.get(ids).getAlamat();
        String nik = String.valueOf(master.get(ids).getNik());
        String ttl = master.get(ids).getTtl();
        String jnk = master.get(ids).getJenis_kelamin();
//System.out.println(ids);
//System.out.println(nama);
//System.out.println(alamat);
//System.out.println(nik);
//System.out.println(ttl);
//System.out.println(jnk);
        txt_no_rm.setText(se);
        txt_nama_pasien.setText(nama);
        txt_nik.setText(nik);
        txt_alamat.setText(alamat);
        txt_ttl.setText(ttl);
        if (jnk.equals("Laki-Laki")) {
            cmb_jeniskelamin.setSelectedIndex(0);
        } else {
            cmb_jeniskelamin.setSelectedIndex(1);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_nik = new javax.swing.JTextField();
        txt_no_rm = new javax.swing.JTextField();
        txt_alamat = new javax.swing.JTextField();
        cmb_jeniskelamin = new view.swing.Combobox();
        txt_ttl = new javax.swing.JTextField();
        txt_nama_pasien = new javax.swing.JTextField();
        kembali = new javax.swing.JLabel();
        btnselanjutnya = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setLayout(null);

        txt_nik.setBackground(new Color(0,0,0,0));
        txt_nik.setBorder(null);
        add(txt_nik);
        txt_nik.setBounds(530, 390, 580, 40);

        txt_no_rm.setBackground(new Color(0,0,0,0)
        );
        txt_no_rm.setBorder(null);
        add(txt_no_rm);
        txt_no_rm.setBounds(530, 250, 580, 40);

        txt_alamat.setBackground(new Color(0,0,0,0));
        txt_alamat.setBorder(null);
        add(txt_alamat);
        txt_alamat.setBounds(530, 460, 580, 40);

        cmb_jeniskelamin.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Laki - Laki", "Perempuan" }));
        cmb_jeniskelamin.setLabeText("Pilih Kelamin");
        cmb_jeniskelamin.setLineColor(new java.awt.Color(0, 153, 153));
        cmb_jeniskelamin.setName(""); // NOI18N
        add(cmb_jeniskelamin);
        cmb_jeniskelamin.setBounds(560, 600, 290, 40);

        txt_ttl.setBackground(new Color(0,0,0,0));
        txt_ttl.setBorder(null);
        add(txt_ttl);
        txt_ttl.setBounds(530, 530, 580, 40);

        txt_nama_pasien.setBackground(new Color(0,0,0,0));
        txt_nama_pasien.setBorder(null);
        add(txt_nama_pasien);
        txt_nama_pasien.setBounds(530, 320, 580, 40);

        kembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btnbatal1_1.png"))); // NOI18N
        kembali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kembaliMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                kembaliMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                kembaliMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                kembaliMousePressed(evt);
            }
        });
        add(kembali);
        kembali.setBounds(10, 710, 150, 51);

        btnselanjutnya.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btnselanjutnya1.png"))); // NOI18N
        btnselanjutnya.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnselanjutnyaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnselanjutnyaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnselanjutnyaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnselanjutnyaMousePressed(evt);
            }
        });
        add(btnselanjutnya);
        btnselanjutnya.setBounds(1110, 710, 250, 51);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebg/Edit Pasien Baru.png"))); // NOI18N
        add(bg);
        bg.setBounds(0, 0, 1366, 768);
    }// </editor-fold>//GEN-END:initComponents

    private void btnselanjutnyaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnselanjutnyaMouseClicked
    String nama = txt_nama_pasien.getText();
        String alamat = txt_alamat.getText();
        int nik = Integer.valueOf(txt_nik.getText());
        String ttl = txt_ttl.getText();
//        jnkk = cmb_jeniskelamin.getItemAt(0).toString();
        Object selectedItem = cmb_jeniskelamin.getSelectedItem();
        
    jnkk = selectedItem.toString();
        System.out.println(ids);
        System.out.println(nama);
        System.out.println(alamat);
        System.out.println(nik);
        System.out.println(ttl);
        System.out.println(selectedItem);

        if( !se.equals("")){
        data_master apa = new data_master(nama, nik, alamat, ttl, jnkk);
        master.updatebynorm(apa);
        main main =(main)SwingUtilities.getWindowAncestor(this);
        this.setVisible(false);
        main.showdatamaster();
        validasiberhasil ac = new validasiberhasil(main, "Data Berhasil Di edit");
            ac.showPopUp();

    } else {
        System.out.println("id tidak ditemukan");
    }
    }//GEN-LAST:event_btnselanjutnyaMouseClicked

    private void kembaliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kembaliMouseClicked
    main main =(main)SwingUtilities.getWindowAncestor(this);
        this.setVisible(false);
        main.showdatamaster();
    }//GEN-LAST:event_kembaliMouseClicked

    private void kembaliMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kembaliMouseEntered
    kembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btnbatal2_1.png")));
    }//GEN-LAST:event_kembaliMouseEntered

    private void kembaliMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kembaliMouseExited
    kembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btnbatal1_1.png")));
    }//GEN-LAST:event_kembaliMouseExited

    private void kembaliMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kembaliMousePressed
    kembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btnbatal3_1.png")));
    }//GEN-LAST:event_kembaliMousePressed

    private void btnselanjutnyaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnselanjutnyaMouseEntered
    btnselanjutnya.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btnselanjutnya2.png")));
    }//GEN-LAST:event_btnselanjutnyaMouseEntered

    private void btnselanjutnyaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnselanjutnyaMouseExited
    btnselanjutnya.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btnselanjutnya1.png")));
    }//GEN-LAST:event_btnselanjutnyaMouseExited

    private void btnselanjutnyaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnselanjutnyaMousePressed
    btnselanjutnya.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btnselanjutnya3.png")));
    }//GEN-LAST:event_btnselanjutnyaMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JLabel btnselanjutnya;
    private view.swing.Combobox cmb_jeniskelamin;
    private javax.swing.JLabel kembali;
    public javax.swing.JTextField txt_alamat;
    public javax.swing.JTextField txt_nama_pasien;
    public javax.swing.JTextField txt_nik;
    public javax.swing.JTextField txt_no_rm;
    public javax.swing.JTextField txt_ttl;
    // End of variables declaration//GEN-END:variables
}
