/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panel;

import java.awt.Color;
import entity.data_master;
import java.awt.Font;
import javax.swing.SwingUtilities;
import main.main;
import repository.data_masterRepository;
import view.swing.validasiberhasil;
import view.swing.validasiberhasil1;

/**
 *
 * @author RESCOM-1
 */
public class datamaster_edit extends javax.swing.JPanel {
    data_masterRepository master = new data_masterRepository();
    datamaster a = new datamaster();
    private int ids = a.id;
    private String se = a.ids;
    private String jnkk;
    private String keterangan;
    private String statusakhir;
    private String tujuhhuruf;
    /**
     * Creates new form datamaster_edit
     */
    public datamaster_edit() {
        initComponents();
        jPanel1.setVisible(false);
        Font font = new Font("Quicksand", Font.PLAIN, 22);
        txt_alamat.setFont(font);
        txt_nama_pasien.setFont(font);
        txt_nik.setFont(font);
        txt_no_rm.setFont(font);
        txt_ttl.setFont(font);
        System.out.println(ids);
        tampil();

    }
    public void tampil(){
//        int id = master.get(ids).getId();
        String nama = master.get(ids).getNama();
        String alamat = master.get(ids).getAlamat();
        String nik = String.valueOf(master.get(ids).getNik());
        String ttl = master.get(ids).getTtl();
        String jnk = master.get(ids).getJenis_kelamin();
        String status = master.get(ids).getStatus_pembayaran();
        String empathuruf = status.substring(0, 4);
        if(status.length() > 4){
               tujuhhuruf = status.substring(0, 7); 
            }
        
        
        
        System.out.println(empathuruf + "  " + tujuhhuruf);
        
//System.out.println(ids);
//System.out.println(nama);
//System.out.println(alamat);
//System.out.println(nik);
//System.out.println(ttl);
//System.out.println(jnk);
        txt_no_rm.setText(se);
        txt_nama_pasien.setText(nama);
        txt_nik.setText(nik);
        txt_alamat.setText(alamat);
        txt_ttl.setText(ttl);
        if (jnk.equals("Laki-Laki")) {
            cmb_jeniskelamin.setSelectedIndex(0);
        } else {
            cmb_jeniskelamin.setSelectedIndex(1);
        }
        if(empathuruf.equals("Umum")){
            cmb_status.setSelectedIndex(0);
        }else if(empathuruf.equals("BPJS")){
            cmb_status.setSelectedIndex(1);
        }else{
            cmb_status.setSelectedIndex(2);
            keterangan = status.substring(11);
            txt_keterangan.setText(keterangan);
            
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_nik = new javax.swing.JTextField();
        txt_no_rm = new javax.swing.JTextField();
        txt_alamat = new javax.swing.JTextField();
        cmb_status = new view.swing.Combobox();
        cmb_jeniskelamin = new view.swing.Combobox();
        txt_ttl = new javax.swing.JTextField();
        txt_nama_pasien = new javax.swing.JTextField();
        kembali = new javax.swing.JLabel();
        btnselanjutnya = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txt_keterangan = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setLayout(null);

        txt_nik.setBackground(new Color(0,0,0,0));
        txt_nik.setBorder(null);
        add(txt_nik);
        txt_nik.setBounds(530, 370, 580, 40);

        txt_no_rm.setBackground(new Color(0,0,0,0)
        );
        txt_no_rm.setBorder(null);
        add(txt_no_rm);
        txt_no_rm.setBounds(530, 230, 580, 40);

        txt_alamat.setBackground(new Color(0,0,0,0));
        txt_alamat.setBorder(null);
        add(txt_alamat);
        txt_alamat.setBounds(530, 440, 580, 40);

        cmb_status.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Umum", "BPJS", "Asuransi" }));
        cmb_status.setLabeText("Pilih Status Pembayaran");
        cmb_status.setLineColor(new java.awt.Color(0, 153, 153));
        cmb_status.setName(""); // NOI18N
        cmb_status.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmb_statusMouseClicked(evt);
            }
        });
        cmb_status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_statusActionPerformed(evt);
            }
        });
        cmb_status.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cmb_statusKeyReleased(evt);
            }
        });
        add(cmb_status);
        cmb_status.setBounds(560, 650, 200, 40);

        cmb_jeniskelamin.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Laki - Laki", "Perempuan" }));
        cmb_jeniskelamin.setLabeText("Pilih Kelamin");
        cmb_jeniskelamin.setLineColor(new java.awt.Color(0, 153, 153));
        cmb_jeniskelamin.setName(""); // NOI18N
        add(cmb_jeniskelamin);
        cmb_jeniskelamin.setBounds(560, 580, 200, 40);

        txt_ttl.setBackground(new Color(0,0,0,0));
        txt_ttl.setBorder(null);
        add(txt_ttl);
        txt_ttl.setBounds(530, 510, 580, 40);

        txt_nama_pasien.setBackground(new Color(0,0,0,0));
        txt_nama_pasien.setBorder(null);
        add(txt_nama_pasien);
        txt_nama_pasien.setBounds(530, 300, 580, 40);

        kembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btnbatal1_1.png"))); // NOI18N
        kembali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kembaliMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                kembaliMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                kembaliMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                kembaliMousePressed(evt);
            }
        });
        add(kembali);
        kembali.setBounds(10, 710, 150, 51);

        btnselanjutnya.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btnselanjutnya1.png"))); // NOI18N
        btnselanjutnya.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnselanjutnyaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnselanjutnyaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnselanjutnyaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnselanjutnyaMousePressed(evt);
            }
        });
        add(btnselanjutnya);
        btnselanjutnya.setBounds(1110, 710, 250, 51);

        jPanel1.setBackground(new Color(0,0,0,0));
        jPanel1.setLayout(null);

        txt_keterangan.setBackground(new Color(0,0,0,0));
        txt_keterangan.setBorder(null);
        jPanel1.add(txt_keterangan);
        txt_keterangan.setBounds(20, 20, 330, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebg/bg keterangan.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 10, 360, 60);

        add(jPanel1);
        jPanel1.setBounds(780, 636, 370, 70);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebg/bg edit pasien.png"))); // NOI18N
        add(bg);
        bg.setBounds(0, 0, 1366, 768);
    }// </editor-fold>//GEN-END:initComponents

    private void btnselanjutnyaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnselanjutnyaMouseClicked
    String nama = txt_nama_pasien.getText();
        String alamat = txt_alamat.getText();
        String nik = txt_nik.getText();
        String ttl = txt_ttl.getText();
//        jnkk = cmb_jeniskelamin.getItemAt(0).toString();
        Object selectedItem = cmb_jeniskelamin.getSelectedItem();
        
    jnkk = selectedItem.toString();
        Object selectedItem1 = cmb_status.getSelectedItem();
        String status = selectedItem1.toString();
        if (status.equals("Asuransi")){
            statusakhir = status + " , " + txt_keterangan.getText();
        } else {
            statusakhir = status ;
        }

        if( !se.equals("")){
        data_master apa = new data_master(txt_no_rm.getText(),nama, nik, alamat, ttl, jnkk,statusakhir);
        master.updatebynorm(apa);
        main main =(main)SwingUtilities.getWindowAncestor(this);
        this.setVisible(false);
        main.showdatamaster();
        validasiberhasil1 ac = new validasiberhasil1(main);
            ac.showPopUp();
            
    } else {
        System.out.println("id tidak ditemukan");
    }
    }//GEN-LAST:event_btnselanjutnyaMouseClicked

    private void kembaliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kembaliMouseClicked
    main main =(main)SwingUtilities.getWindowAncestor(this);
        this.setVisible(false);
        main.showdatamaster();
    }//GEN-LAST:event_kembaliMouseClicked

    private void kembaliMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kembaliMouseEntered
    kembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btnbatal2_1.png")));
    }//GEN-LAST:event_kembaliMouseEntered

    private void kembaliMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kembaliMouseExited
    kembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btnbatal1_1.png")));
    }//GEN-LAST:event_kembaliMouseExited

    private void kembaliMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kembaliMousePressed
    kembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btnbatal3_1.png")));
    }//GEN-LAST:event_kembaliMousePressed

    private void btnselanjutnyaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnselanjutnyaMouseEntered
    btnselanjutnya.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btnselanjutnya2.png")));
    }//GEN-LAST:event_btnselanjutnyaMouseEntered

    private void btnselanjutnyaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnselanjutnyaMouseExited
    btnselanjutnya.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btnselanjutnya1.png")));
    }//GEN-LAST:event_btnselanjutnyaMouseExited

    private void btnselanjutnyaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnselanjutnyaMousePressed
    btnselanjutnya.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btnselanjutnya3.png")));
    }//GEN-LAST:event_btnselanjutnyaMousePressed

    private void cmb_statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_statusActionPerformed
    if (cmb_status.getSelectedIndex() == 2) { // Pilihan ke-3
                    
        jPanel1.setVisible(true);
                } else {
        jPanel1.setVisible(false);
    }
    }//GEN-LAST:event_cmb_statusActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseClicked

    private void cmb_statusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmb_statusMouseClicked
    
    }//GEN-LAST:event_cmb_statusMouseClicked

    private void cmb_statusKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmb_statusKeyReleased
    
    }//GEN-LAST:event_cmb_statusKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JLabel btnselanjutnya;
    private view.swing.Combobox cmb_jeniskelamin;
    private view.swing.Combobox cmb_status;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel kembali;
    public javax.swing.JTextField txt_alamat;
    public javax.swing.JTextField txt_keterangan;
    public javax.swing.JTextField txt_nama_pasien;
    public javax.swing.JTextField txt_nik;
    public javax.swing.JTextField txt_no_rm;
    public javax.swing.JTextField txt_ttl;
    // End of variables declaration//GEN-END:variables
}
