/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.swing;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

/**
 *
 * @author semafie
 */
public class itempoli extends javax.swing.JPanel {
private final List<EventMenuSelected> events = new ArrayList<>();
    private int index;
    private boolean selected;
    private boolean mouseOver;
    private JPanel containerPanel;
    
    
    public int getIndex() {
        return index;
    }

    public void setIndex(int index) {
        this.index = index;
    }

    public boolean isSelected() {
        return selected;
    }

    public void setSelected(boolean selected) {
        this.selected = selected;
        itempoli.setVisible(!selected);
        itempoliselected.setVisible(selected);
        repaint();
    }
    public itempoli() {
        initComponents();
        itempoliselected.setVisible(false);
        setOpaque(false);
        this.index = index;
        addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                mouseOver = true;
                repaint();
            }

            @Override
            public void mouseExited(MouseEvent e) {
                mouseOver = false;
                repaint();
            }
            @Override
            public void mouseReleased(MouseEvent me) {
                if (SwingUtilities.isLeftMouseButton(me)) {
                    if (mouseOver) {
                        setSelected(true);
                        repaint();
                        runEvent();
                    }
                }
            }
        });
    }
    private void runEvent() {
        for (EventMenuSelected event : events) {
            event.selected(index);
        }
    }

    public void addEvent(EventMenuSelected event) {
        events.add(event);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtpoli = new javax.swing.JLabel();
        itempoli = new javax.swing.JLabel();
        itempoliselected = new javax.swing.JLabel();

        setLayout(null);
        add(txtpoli);
        txtpoli.setBounds(50, 20, 320, 30);

        itempoli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebg/bgitempoli2.png"))); // NOI18N
        add(itempoli);
        itempoli.setBounds(0, 0, 411, 82);

        itempoliselected.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebg/bgitempoli1.png"))); // NOI18N
        add(itempoliselected);
        itempoliselected.setBounds(0, 0, 410, 80);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel itempoli;
    private javax.swing.JLabel itempoliselected;
    public static javax.swing.JLabel txtpoli;
    // End of variables declaration//GEN-END:variables
}
