/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view.swing;

import entity.history_datamaster;
import java.awt.Font;
import javax.swing.JFrame;
import javax.swing.SwingConstants;
import javax.swing.SwingUtilities;
import main.main;
import panel.Login;
import repository.history_datamasterRepository;
import repository.userRepository;
import service.Auth;

/**
 *
 * @author RESCOM-1
 */
public class validasiberhasil1 extends Dialog {
    private int aaa;
    private int iduser;
    private String nama;
    
    /**
     * Creates new form validasiberhasil
     */
    public validasiberhasil1(JFrame fram) {
        super(fram);
        initComponents();
        Font font = new Font("Quicksand", Font.BOLD, 30);
        txt_peringatan.setFont(font);
        txt_peringatan.setHorizontalAlignment(SwingConstants.CENTER);
        txt_peringatan.setText("Data berhasil Di Edit");
        Auth apa1 = new Auth();
        iduser = apa1.id;
        userRepository apa2 = new userRepository();
        nama = apa2.get(iduser).getUsername();
        System.out.println(nama);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_peringatan = new javax.swing.JLabel();
        button = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(txt_peringatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 500, 50));

        button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btnoke1.png"))); // NOI18N
        button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttonMousePressed(evt);
            }
        });
        getContentPane().add(button, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 120, 40));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagetxt/Validasi Jamaah ( Tambah ).png"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 333));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMouseClicked
        history_datamasterRepository apa = new history_datamasterRepository();
        int id = apa.getlastid().getId();
        
        
        history_datamaster cie = new history_datamaster(id,"Di Edit",nama);
        apa.update(cie);
    closeMessage();
    
    }//GEN-LAST:event_buttonMouseClicked

    private void buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMouseEntered
    button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btnoke2.png")));
    }//GEN-LAST:event_buttonMouseEntered

    private void buttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMouseExited
    button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btnoke1.png")));
    }//GEN-LAST:event_buttonMouseExited

    private void buttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMousePressed
    button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btnoke3.png")));
    }//GEN-LAST:event_buttonMousePressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JLabel button;
    private javax.swing.JLabel txt_peringatan;
    // End of variables declaration//GEN-END:variables
}
