/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view.swing;

import javax.swing.JFrame;
import panel.Login;

/**
 *
 * @author RESCOM-1
 */
public class validasikonfirmasi extends Dialog {

    /**
     * Creates new form validasikonfirmasi
     */
    public validasikonfirmasi(JFrame fram) {
        super(fram);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_ya = new javax.swing.JLabel();
        btn_tidak = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        btn_ya.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagetxt/btnya1.png"))); // NOI18N
        btn_ya.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_yaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_yaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_yaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_yaMousePressed(evt);
            }
        });
        getContentPane().add(btn_ya);
        btn_ya.setBounds(320, 250, 120, 40);

        btn_tidak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagetxt/btntidak1.png"))); // NOI18N
        btn_tidak.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_tidakMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_tidakMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_tidakMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_tidakMousePressed(evt);
            }
        });
        getContentPane().add(btn_tidak);
        btn_tidak.setBounds(140, 250, 120, 40);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagetxt/Validasirequest.png"))); // NOI18N
        getContentPane().add(bg);
        bg.setBounds(0, 0, 580, 330);

        setSize(new java.awt.Dimension(592, 340));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_tidakMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_tidakMouseClicked
    closeMessage();
    }//GEN-LAST:event_btn_tidakMouseClicked

    private void btn_yaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_yaMouseClicked
    Login aa = new Login();
    aa.setVisible(false);
    closeMessage();
    }//GEN-LAST:event_btn_yaMouseClicked

    private void btn_yaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_yaMouseEntered
    btn_ya.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagetxt/btnya2.png")));
    }//GEN-LAST:event_btn_yaMouseEntered

    private void btn_yaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_yaMouseExited
    btn_ya.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagetxt/btnya1.png")));
    }//GEN-LAST:event_btn_yaMouseExited

    private void btn_yaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_yaMousePressed
    btn_ya.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagetxt/btnya3.png")));
    }//GEN-LAST:event_btn_yaMousePressed

    private void btn_tidakMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_tidakMouseEntered
    btn_tidak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagetxt/btntidak2.png")));
    }//GEN-LAST:event_btn_tidakMouseEntered

    private void btn_tidakMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_tidakMouseExited
    btn_tidak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagetxt/btntidak1.png")));
    }//GEN-LAST:event_btn_tidakMouseExited

    private void btn_tidakMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_tidakMousePressed
    btn_tidak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagetxt/btntidak3.png")));
    }//GEN-LAST:event_btn_tidakMousePressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JLabel btn_tidak;
    private javax.swing.JLabel btn_ya;
    // End of variables declaration//GEN-END:variables
}
