/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panel;

import javax.swing.SwingUtilities;
import main.main;

/**
 *
 * @author RESCOM-1
 */
public class Dasboard extends javax.swing.JPanel {

    /**
     * Creates new form Dasboard
     */
    public Dasboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btndatamaster = new javax.swing.JLabel();
        btndatadokter = new javax.swing.JLabel();
        btnpasienbaru = new javax.swing.JLabel();
        btnpasienlama = new javax.swing.JLabel();
        btnrekapharian = new javax.swing.JLabel();
        btnlogout = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1366, 768));
        setLayout(null);

        btndatamaster.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btndatamaster1.png"))); // NOI18N
        btndatamaster.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btndatamasterMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btndatamasterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btndatamasterMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btndatamasterMousePressed(evt);
            }
        });
        add(btndatamaster);
        btndatamaster.setBounds(200, 150, 380, 100);

        btndatadokter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btndatadokter1.png"))); // NOI18N
        btndatadokter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btndatadokterMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btndatadokterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btndatadokterMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btndatadokterMousePressed(evt);
            }
        });
        add(btndatadokter);
        btndatadokter.setBounds(620, 150, 380, 100);

        btnpasienbaru.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btnpasienbaru1.png"))); // NOI18N
        btnpasienbaru.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnpasienbaruMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnpasienbaruMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnpasienbaruMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnpasienbaruMousePressed(evt);
            }
        });
        add(btnpasienbaru);
        btnpasienbaru.setBounds(420, 290, 370, 140);

        btnpasienlama.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btnpasienlama1.png"))); // NOI18N
        btnpasienlama.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnpasienlamaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnpasienlamaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnpasienlamaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnpasienlamaMousePressed(evt);
            }
        });
        add(btnpasienlama);
        btnpasienlama.setBounds(720, 450, 360, 130);

        btnrekapharian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btnrekapharian1.png"))); // NOI18N
        btnrekapharian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnrekapharianMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnrekapharianMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnrekapharianMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnrekapharianMousePressed(evt);
            }
        });
        add(btnrekapharian);
        btnrekapharian.setBounds(930, 610, 380, 90);

        btnlogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btnlogout1.png"))); // NOI18N
        btnlogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnlogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnlogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnlogoutMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnlogoutMousePressed(evt);
            }
        });
        add(btnlogout);
        btnlogout.setBounds(20, 700, 180, 51);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebg/bg dasboard.png"))); // NOI18N
        add(bg);
        bg.setBounds(0, -2, 1366, 770);
    }// </editor-fold>//GEN-END:initComponents

    private void btndatamasterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndatamasterMouseClicked
    main main =(main)SwingUtilities.getWindowAncestor(this);
    this.setVisible(false);
    main.showdatamaster();
    }//GEN-LAST:event_btndatamasterMouseClicked

    private void btndatadokterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndatadokterMouseClicked
    main main =(main)SwingUtilities.getWindowAncestor(this);
    this.setVisible(false);
    main.showdatadokter();
    }//GEN-LAST:event_btndatadokterMouseClicked

    private void btnpasienbaruMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnpasienbaruMouseClicked
    pasienbaru a = new pasienbaru();
//    a.txt_alamat.setText("");
//    a.txt_nama_pasien.setText("");
//    a.txt_nik.setText("");
//    a.txt_no_rm.setText("");
//    a.txt_ttl.setText("");
    main main =(main)SwingUtilities.getWindowAncestor(this);
    this.setVisible(false);
    main.showpasienbaru();
    }//GEN-LAST:event_btnpasienbaruMouseClicked

    private void btnpasienlamaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnpasienlamaMouseClicked
    main main =(main)SwingUtilities.getWindowAncestor(this);
    this.setVisible(false);
    main.showpasienlama();
    }//GEN-LAST:event_btnpasienlamaMouseClicked

    private void btnrekapharianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnrekapharianMouseClicked
    main main =(main)SwingUtilities.getWindowAncestor(this);
    this.setVisible(false);
    main.showrekapharian();
    }//GEN-LAST:event_btnrekapharianMouseClicked

    private void btnlogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlogoutMouseClicked
    main main =(main)SwingUtilities.getWindowAncestor(this);
    this.setVisible(false);
    main.showlogin();
    }//GEN-LAST:event_btnlogoutMouseClicked

    private void btnlogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlogoutMouseEntered
    btnlogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btnlogout2.png")));
    }//GEN-LAST:event_btnlogoutMouseEntered

    private void btnlogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlogoutMouseExited
    btnlogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btnlogout1.png")));
    }//GEN-LAST:event_btnlogoutMouseExited

    private void btnlogoutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnlogoutMousePressed
    btnlogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btnlogout3.png")));
    }//GEN-LAST:event_btnlogoutMousePressed

    private void btndatamasterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndatamasterMouseEntered
    btndatamaster.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btndatamaster2.png")));
    }//GEN-LAST:event_btndatamasterMouseEntered

    private void btndatamasterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndatamasterMouseExited
    btndatamaster.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btndatamaster1.png")));
    }//GEN-LAST:event_btndatamasterMouseExited

    private void btndatamasterMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndatamasterMousePressed
    btndatamaster.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btndatamaster3.png")));
    }//GEN-LAST:event_btndatamasterMousePressed

    private void btndatadokterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndatadokterMouseEntered
    btndatadokter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btndatadokter2.png")));
    }//GEN-LAST:event_btndatadokterMouseEntered

    private void btndatadokterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndatadokterMouseExited
    btndatadokter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btndatadokter1.png")));
    }//GEN-LAST:event_btndatadokterMouseExited

    private void btndatadokterMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndatadokterMousePressed
    btndatadokter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btndatadokter3.png")));
    }//GEN-LAST:event_btndatadokterMousePressed

    private void btnrekapharianMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnrekapharianMouseEntered
    btnrekapharian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btnrekapharian2.png")));
    }//GEN-LAST:event_btnrekapharianMouseEntered

    private void btnrekapharianMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnrekapharianMouseExited
    btnrekapharian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btnrekapharian1.png")));
    }//GEN-LAST:event_btnrekapharianMouseExited

    private void btnrekapharianMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnrekapharianMousePressed
    btnrekapharian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btnrekapharian3.png")));
    }//GEN-LAST:event_btnrekapharianMousePressed

    private void btnpasienbaruMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnpasienbaruMouseEntered
    btnpasienbaru.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btnpasienbaru2.png")));
    }//GEN-LAST:event_btnpasienbaruMouseEntered

    private void btnpasienbaruMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnpasienbaruMouseExited
    btnpasienbaru.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btnpasienbaru1.png")));
    }//GEN-LAST:event_btnpasienbaruMouseExited

    private void btnpasienbaruMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnpasienbaruMousePressed
    btnpasienbaru.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btnpasienbaru3.png")));
    }//GEN-LAST:event_btnpasienbaruMousePressed

    private void btnpasienlamaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnpasienlamaMouseEntered
    btnpasienlama.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btnpasienlama2.png")));
    }//GEN-LAST:event_btnpasienlamaMouseEntered

    private void btnpasienlamaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnpasienlamaMouseExited
    btnpasienlama.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btnpasienlama1.png")));
    }//GEN-LAST:event_btnpasienlamaMouseExited

    private void btnpasienlamaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnpasienlamaMousePressed
    btnpasienlama.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagebtn/btnpasienlama3.png")));
    }//GEN-LAST:event_btnpasienlamaMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JLabel btndatadokter;
    private javax.swing.JLabel btndatamaster;
    private javax.swing.JLabel btnlogout;
    private javax.swing.JLabel btnpasienbaru;
    private javax.swing.JLabel btnpasienlama;
    private javax.swing.JLabel btnrekapharian;
    // End of variables declaration//GEN-END:variables
}
